import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { knowledgeTransfers, prepareKnowledge, writeKnowledgeChecklist } from '../../scripts/installer/knowledge.js';
import { runInstallWizard } from '../../scripts/installer/terminal.js';
const temp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'installer-knowledge-'));

test('UT-010 replacement yields source, destination, reason, and pending status', () => { const items = knowledgeTransfers({ actions: [{ path: 'AGENTS.md', kind: 'replace' }] }, '.my-workflow/backups/now'); assert.deepEqual(items[0], { source: '.my-workflow/backups/now/files/AGENTS.md', destination: 'docs/product/AGENT-CONTEXT.md', reason: 'Consumer-authored instructions require manual review.', status: 'Pending human transfer' }); });
test('IT-004 checklist is written inside the backup only', () => { const root = temp(); const backup = path.join(root, 'backup'); fs.mkdirSync(backup); const items = knowledgeTransfers({ actions: [{ path: 'AGENTS.md', kind: 'replace' }] }, backup); const result = writeKnowledgeChecklist(backup, items); assert.equal(result, path.join(backup, 'knowledge-transfer.md')); assert.match(fs.readFileSync(result, 'utf8'), /Pending human transfer/); assert.equal(fs.existsSync(path.join(root, 'knowledge', 'AGENTS.md')), false); });
test('E2E-002 fresh scaffold has no transfer artifact or source content', () => { const root = temp(); const items = prepareKnowledge({ actions: [{ path: 'knowledge/AGENTS.md', kind: 'add' }] }, { targetRoot: root, backup: null }); assert.deepEqual(items, []); assert.deepEqual(fs.readdirSync(root), []); });
test('E2E-002 accepted consumer guidance replacement leaves an inspectable checklist', async () => { const root = temp(); await runInstallWizard({ sourceRoot: path.resolve(import.meta.dirname, '../..'), targetRoot: root, ...feed(['1', 'y', 'y']) }); const agents = path.join(root, 'AGENTS.md'); const original = fs.readFileSync(agents, 'utf8'); fs.writeFileSync(agents, original.replace('<!-- my-workflow:core:end -->', 'consumer-specific context\n<!-- my-workflow:core:end -->')); const output = []; const result = await runInstallWizard({ sourceRoot: path.resolve(import.meta.dirname, '../..'), targetRoot: root, ...feed(['1', 'y', '1', 'y'], output) }); assert.equal(result.code, 0); assert.equal(result.knowledge.length, 1); const checklist = fs.readFileSync(path.join(root, result.result.backup, 'knowledge-transfer.md'), 'utf8'); assert.match(checklist, /Pending human transfer/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'docs/product/AGENT-CONTEXT.md'), 'utf8'), /consumer-specific context/); assert.match(output.join('\n'), /Checklist:/); });
function feed(values, output = []) { let index = 0; return { input: async () => values[index++], write: (value) => output.push(value) }; }
