import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { knowledgeTransfers, prepareKnowledge, writeKnowledgeChecklist } from '../../scripts/installer/knowledge.js';
import { runInstallWizard } from '../../scripts/installer/terminal.js';
const temp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'installer-knowledge-'));

test('UT-010 replacement yields source, destination, reason, and pending status', () => { const items = knowledgeTransfers({ actions: [{ path: 'AGENTS.md', kind: 'replace' }] }, '.my-workflow/backups/now'); assert.deepEqual(items[0], { source: '.my-workflow/backups/now/files/AGENTS.md', destination: 'docs/product/AGENT-CONTEXT.md', reason: 'Consumer-authored instructions require manual review.', status: 'Pending human transfer' }); });
test('IT-004 checklist is written inside the backup only', () => { const root = temp(); const backup = path.join(root, 'backup'); fs.mkdirSync(backup); const items = knowledgeTransfers({ actions: [{ path: 'AGENTS.md', kind: 'replace' }] }, backup); const result = writeKnowledgeChecklist(backup, items); assert.equal(result, path.join(backup, 'knowledge-transfer.md')); assert.match(fs.readFileSync(result, 'utf8'), /Pending human transfer/); assert.equal(fs.existsSync(path.join(root, 'knowledge', 'AGENTS.md')), false); });
test('E2E-002 fresh scaffold has no transfer artifact or source content', () => { const root = temp(); const items = prepareKnowledge({ actions: [{ path: 'knowledge/AGENTS.md', kind: 'add' }] }, { targetRoot: root, backup: null }); assert.deepEqual(items, []); assert.deepEqual(fs.readdirSync(root), []); });
test('E2E-002 accepted consumer guidance replacement leaves an inspectable checklist', async () => { const root = temp(); await runInstallWizard({ sourceRoot: path.resolve(import.meta.dirname, '../..'), targetRoot: root, ...feed(['1', 'y', 'y']) }); const agents = path.join(root, 'AGENTS.md'); const original = fs.readFileSync(agents, 'utf8'); fs.writeFileSync(agents, original.replace('<!-- my-workflow:core:end -->', 'consumer-specific context\n<!-- my-workflow:core:end -->')); const output = []; const result = await runInstallWizard({ sourceRoot: path.resolve(import.meta.dirname, '../..'), targetRoot: root, ...feed(['1', 'y', '1', 'y'], output) }); assert.equal(result.code, 0); assert.equal(result.knowledge.length, 1); const checklist = fs.readFileSync(path.join(root, result.result.backup, 'knowledge-transfer.md'), 'utf8'); assert.match(checklist, /Pending human transfer/); assert.doesNotMatch(fs.readFileSync(path.join(root, 'docs/product/AGENT-CONTEXT.md'), 'utf8'), /consumer-specific context/); assert.match(output.join('\n'), /Checklist:/); });
function feed(values, output = []) { let index = 0; return { input: async () => values[index++], write: (value) => output.push(value) }; }

test('IT-004 accepted knowledge replacement preserves original bytes and mode beside exact new package bytes', async () => { const root = temp(); const source = path.resolve(import.meta.dirname, '../..'); await runInstallWizard({ sourceRoot: source, targetRoot: root, ...feed(['1', 'y', 'y']) }); const agents = path.join(root, 'AGENTS.md'); const original = fs.readFileSync(agents); fs.chmodSync(agents, 0o640); const originalMode = fs.statSync(agents).mode & 0o7777; const modified = Buffer.from(original.toString().replace('<!-- my-workflow:core:end -->', 'consumer guidance\n<!-- my-workflow:core:end -->')); fs.writeFileSync(agents, modified); const result = await runInstallWizard({ sourceRoot: source, targetRoot: root, ...feed(['1', 'y', '1', 'y']) }); assert.equal(result.code, 0); const backup = path.join(root, result.result.backup, 'files/AGENTS.md'); assert.deepEqual(fs.readFileSync(backup), modified); assert.equal(fs.statSync(backup).mode & 0o7777, originalMode); assert.deepEqual(fs.readFileSync(agents), fs.readFileSync(path.join(source, 'AGENTS.md'))); assert.equal(fs.readFileSync(agents, 'utf8').includes('consumer guidance'), false); assert.equal(fs.readFileSync(path.join(root, '.my-workflow/adoption.json'), 'utf8').includes('consumer guidance'), false); });
test('E2E-002 old and new packed installers preserve knowledge through a safe upgrade', async () => { const source = path.resolve(import.meta.dirname, '../..'); const oldPack = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-old-pack-')); const newPack = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-new-pack-')); const oldTarball = path.join(oldPack, JSON.parse(execFileSync('npm', ['pack', '--pack-destination', oldPack, '--json'], { cwd: source, encoding: 'utf8' }))[0].filename); const newTarball = path.join(newPack, JSON.parse(execFileSync('npm', ['pack', '--pack-destination', newPack, '--json'], { cwd: source, encoding: 'utf8' }))[0].filename); const consumer = temp(); execFileSync('npm', ['install', '--ignore-scripts', '--no-package-lock', oldTarball], { cwd: consumer, stdio: 'ignore' }); const oldRoot = path.join(consumer, 'node_modules/workflow-spec-driven'); const oldTerminal = await import(pathToFileURL(path.join(oldRoot, 'scripts/installer/terminal.js')).href); await oldTerminal.runInstallWizard({ sourceRoot: oldRoot, targetRoot: consumer, ...feed(['1', 'y', 'y']) }); const agents = path.join(consumer, 'AGENTS.md'); const modified = Buffer.from(fs.readFileSync(agents, 'utf8').replace('<!-- my-workflow:core:end -->', 'consumer guidance\n<!-- my-workflow:core:end -->')); fs.writeFileSync(agents, modified); execFileSync('npm', ['install', '--ignore-scripts', '--no-package-lock', newTarball], { cwd: consumer, stdio: 'ignore' }); const newRoot = path.join(consumer, 'node_modules/workflow-spec-driven'); const newTerminal = await import(`${pathToFileURL(path.join(newRoot, 'scripts/installer/terminal.js')).href}?new`); const result = await newTerminal.runInstallWizard({ sourceRoot: newRoot, targetRoot: consumer, ...feed(['1', 'y', '1', 'y']) }); assert.equal(result.code, 0); assert.deepEqual(fs.readFileSync(path.join(consumer, result.result.backup, 'files/AGENTS.md')), modified); assert.match(fs.readFileSync(path.join(consumer, result.result.backup, 'knowledge-transfer.md'), 'utf8'), /Source:|Destination:|Reason:|Pending human transfer/); assert.doesNotMatch(fs.readFileSync(agents, 'utf8'), /consumer guidance/); });
