import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { buildPlan } from '../../scripts/installer/engine.js';
import { pathToFileURL } from 'node:url';
const root = path.resolve(import.meta.dirname, '../..');

test('IT-019 package exposes the unscoped executable only', () => { const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')); assert.equal(pkg.name, 'workflow-spec-driven'); assert.deepEqual(Object.keys(pkg.bin), ['workflow-spec-driven']); assert.equal(pkg.bin['workflow-spec-driven'], 'bin/workflow-spec-driven.js'); assert.equal(pkg.files.includes('scripts/adopt.py'), false); });
test('IT-010 pack dry-run includes Node installer and excludes Python adopter', () => { const json = execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: root, encoding: 'utf8' }); const metadata = JSON.parse(json)[0]; const names = metadata.files.map((item) => item.path); assert.ok(names.includes('bin/workflow-spec-driven.js')); assert.ok(names.includes('scripts/installer/engine.js')); assert.ok(names.includes('docs/workflow/repository-intelligence.md')); assert.equal(names.some((name) => name === 'scripts/adopt.py' || name === 'bin/my-workflow.js'), false); });
test('IT-019 package can resolve from a clean directory', () => { const target = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-package-')); const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')); assert.equal(packageJson.engines.node, '>=18.0.0'); assert.ok(target.startsWith(os.tmpdir())); });
test('IT-010 and IT-015 packed executable performs Node-only install and public cancellation probes', async () => {
  const destination = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-tarball-'));
  const json = execFileSync('npm', ['pack', '--pack-destination', destination, '--json'], { cwd: root, encoding: 'utf8' });
  const tarball = path.join(destination, JSON.parse(json)[0].filename);
  const clean = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-clean-'));
  const noPython = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-no-python-'));
  const toolchain = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-toolchain-'));
  fs.symlinkSync(process.execPath, path.join(toolchain, 'node'));
  fs.symlinkSync(execFileSync('which', ['git'], { encoding: 'utf8' }).trim(), path.join(toolchain, 'git'));
  const env = { ...process.env, PATH: `${noPython}:${toolchain}` };
  execFileSync('npm', ['install', '--ignore-scripts', '--no-package-lock', tarball], { cwd: clean });
  execFileSync('git', ['init', '-q'], { cwd: clean, env });
  execFileSync('git', ['config', 'user.email', 'installer@test.invalid'], { cwd: clean, env });
  execFileSync('git', ['config', 'user.name', 'Installer Test'], { cwd: clean, env });
  const canonicalIgnore = buildPlan({ sourceRoot: root, targetRoot: clean, selectedModules: ['core'] }).staged['.gitignore'];
  fs.writeFileSync(path.join(clean, '.gitignore'), Buffer.concat([Buffer.from('node_modules/\n'), canonicalIgnore]));
  const canonicalSearchIgnore = buildPlan({ sourceRoot: root, targetRoot: clean, selectedModules: ['core'] }).staged['.ignore'];
  fs.writeFileSync(path.join(clean, '.ignore'), canonicalSearchIgnore);
  execFileSync('git', ['add', '.gitignore', '.ignore', 'package.json'], { cwd: clean, env });
  execFileSync('git', ['commit', '-qm', 'fixture'], { cwd: clean, env });
  const executable = path.join(clean, 'node_modules/.bin/workflow-spec-driven');
  const clone = () => { const target = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-pty-')); fs.cpSync(clean, target, { recursive: true }); return target; };
  const assertResidueZero = (target) => { assert.equal(execFileSync('git', ['status', '--porcelain'], { cwd: target, env, encoding: 'utf8' }), ''); for (const relative of ['.my-workflow/adoption.json', '.my-workflow/transaction.json', '.my-workflow/backups']) assert.equal(fs.existsSync(path.join(target, relative)), false, relative); };
  const runCancellationProbe = (target, signal) => spawnSync('/usr/bin/expect', ['-c', [`set timeout 60`, `log_user 1`, `spawn -noecho $env(EXEC) install`, `stty rows 24 columns 80`, `expect -re {Modules.*comma-separated} { send "${signal}\\r" }`, `expect "Installation cancelled. No files changed."`, `expect eof`].join('\n')], { cwd: target, env: { ...env, NO_COLOR: '1', EXEC: path.join(target, 'node_modules/.bin/workflow-spec-driven') }, encoding: 'utf8' });
  const eofTarget = clone();
  const eof = runCancellationProbe(eofTarget, '\\004');
  assert.equal(eof.status, 0, `${eof.error?.message || ''} signal=${eof.signal || ''}\n${eof.stderr}\n${eof.stdout}`);
  assert.equal((eof.stdout.match(/Installation cancelled\. No files changed\./g) || []).length, 1, eof.stdout);
  assert.equal(eof.stdout.includes('scripts/install_security_skills.py'), false, eof.stdout);
  assertResidueZero(eofTarget);
  const interruptTarget = clone();
  const interrupt = runCancellationProbe(interruptTarget, '\\003');
  assert.equal(interrupt.status, 0, `${interrupt.error?.message || ''} signal=${interrupt.signal || ''}\n${interrupt.stderr}\n${interrupt.stdout}`);
  assert.equal((interrupt.stdout.match(/Installation cancelled\. No files changed\./g) || []).length, 1, interrupt.stdout);
  assert.equal(interrupt.stdout.includes('scripts/install_security_skills.py'), false, interrupt.stdout);
  assertResidueZero(interruptTarget);
  const normalTarget = clone();
  const normal = spawnSync('/usr/bin/expect', ['-c', [`set timeout 60`, `log_user 1`, `spawn -noecho $env(EXEC) install`, `stty rows 24 columns 80`, `expect -re {Modules.*comma-separated} { send "1\\r" }`, `expect -re {Continue to preview} { send "n\\r" }`, `expect "Installation cancelled. No files changed."`, `expect eof`].join('\n')], { cwd: normalTarget, env: { ...env, EXEC: path.join(normalTarget, 'node_modules/.bin/workflow-spec-driven') }, encoding: 'utf8' });
  assert.equal(normal.status, 0, `${normal.error?.message || ''} signal=${normal.signal || ''}\n${normal.stderr}\n${normal.stdout}`);
  assert.equal((normal.stdout.match(/Installation cancelled\. No files changed\./g) || []).length, 1, normal.stdout);
  assertResidueZero(normalTarget);
  const colorEnv = { ...env };
  delete colorEnv.NO_COLOR;
  const noColor = spawnSync('/usr/bin/expect', ['-c', 'set timeout 60\nlog_user 1\nspawn -noecho $env(EXEC) install\nexpect -re {Modules.*comma-separated} { send "4\\r" }\nexpect -re {Continue to preview} { send "n\\r" }\nexpect "Installation cancelled."\nexpect eof'], { cwd: clean, env: { ...env, NO_COLOR: '1', EXEC: executable }, encoding: 'utf8' });
  assert.equal(noColor.status, 0, `${noColor.error?.message || ''} signal=${noColor.signal || ''}\n${noColor.stderr}\n${noColor.stdout}`);
  const heading = noColor.stdout.indexOf('Workflow Spec-Driven Installer');
  assert.ok(heading >= 0, noColor.stdout);
  assert.equal(/\u001b\[[0-?]*[ -/]*[@-~]/.test(noColor.stdout.slice(heading)), false, noColor.stdout.slice(heading));
  assert.equal((noColor.stdout.match(/Installation cancelled\. No files changed\./g) || []).length, 1, noColor.stdout);
  assertResidueZero(clean);
  const result = spawnSync('/usr/bin/expect', ['-c', 'set timeout 60\nlog_user 1\nspawn -noecho $env(EXEC) install\nexpect -re {Modules.*comma-separated} { send "1\\r" }\nexpect -re {Continue to preview} { send "y\\r" }\nexpect -re {Apply this plan} { send "y\\r" }\nexpect "Installation complete."\nexpect eof'], { cwd: clean, env: { ...colorEnv, EXEC: executable }, encoding: 'utf8' });
  // Keep color-capable TTY behavior covered by the adjacent accepted flow below.
  assert.equal(result.status, 0, `${result.error?.message || ''} signal=${result.signal || ''}\n${result.stderr}\n${result.stdout}`);
  assert.match(result.stdout, /Workflow Spec-Driven Installer/);
  assert.match(result.stdout, /Installation complete\./);
  const cleanRoot = fs.realpathSync(clean);
  const securityCommand = `python3 '${path.join(cleanRoot, 'node_modules/workflow-spec-driven/scripts/install_security_skills.py')}' '${cleanRoot}' --yes`;
  assert.equal(result.stdout.includes(securityCommand), true, result.stdout);
  const manifestPath = path.join(clean, '.my-workflow/adoption.json');
  assert.equal(fs.existsSync(manifestPath), true);
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.deepEqual(manifest.layers, ['core']);
  for (const skill of ['wspecify', 'wdesign', 'wtasks', 'wimplement', 'wverify', 'wreview', 'wqa']) {
    const alias = path.join(clean, '.claude/skills', skill);
    const canonical = path.join(clean, '.agents/skills', skill);
    assert.equal(fs.lstatSync(alias).isSymbolicLink(), true, skill);
    const resolved = fs.realpathSync(alias);
    assert.equal(resolved, fs.realpathSync(canonical), skill);
    assert.ok(resolved.startsWith(`${fs.realpathSync(clean)}${path.sep}`), skill);
    assert.deepEqual(fs.readFileSync(path.join(alias, 'SKILL.md')), fs.readFileSync(path.join(canonical, 'SKILL.md')), skill);
  }
  const expected = buildPlan({ sourceRoot: root, targetRoot: fs.mkdtempSync(path.join(os.tmpdir(), 'installer-expected-')), selectedModules: ['core'] }).manifest;
  assert.deepEqual(manifest.files, expected.files);
  assert.equal(fs.existsSync(path.join(noPython, 'python')), false);
  assert.equal(fs.existsSync(path.join(noPython, 'python3')), false);
  for (const skill of ['security-best-practices', 'security-threat-model', 'security-review']) {
    assert.equal(fs.existsSync(path.join(clean, '.agents/skills', skill)), false, skill);
  }
  assert.equal(env.PATH, `${noPython}:${toolchain}`);
  assert.equal(fs.existsSync(path.join(clean, 'node_modules/workflow-spec-driven/scripts/adopt.py')), false);
  assert.match(execFileSync(executable, ['--help'], { cwd: clean, env, encoding: 'utf8' }), /workflow-spec-driven install/);
  const installedEngine = await import(pathToFileURL(path.join(clean, 'node_modules/workflow-spec-driven/scripts/installer/engine.js')).href);
  const installedManifest = installedEngine.loadManifest(clean);
  assert.deepEqual(installedManifest.layers, ['core']);
  assert.equal(Object.keys(installedManifest.files).length, Object.keys(manifest.files).length);
});
