import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
const root = path.resolve(import.meta.dirname, '../..');

test('IT-019 package exposes the unscoped executable only', () => { const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')); assert.equal(pkg.name, 'workflow-spec-driven'); assert.deepEqual(Object.keys(pkg.bin), ['workflow-spec-driven']); assert.equal(pkg.bin['workflow-spec-driven'], 'bin/workflow-spec-driven.js'); assert.equal(pkg.files.includes('scripts/adopt.py'), false); });
test('IT-010 pack dry-run includes Node installer and excludes Python adopter', () => { const json = execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: root, encoding: 'utf8' }); const metadata = JSON.parse(json)[0]; const names = metadata.files.map((item) => item.path); assert.ok(names.includes('bin/workflow-spec-driven.js')); assert.ok(names.includes('scripts/installer/engine.js')); assert.equal(names.some((name) => name === 'scripts/adopt.py' || name === 'bin/my-workflow.js'), false); });
test('IT-019 package can resolve from a clean directory', () => { const target = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-package-')); const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')); assert.equal(packageJson.engines.node, '>=18.0.0'); assert.ok(target.startsWith(os.tmpdir())); });
test('IT-010 tarball .bin executable runs with Python absent from PATH', async () => { const destination = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-tarball-')); const json = execFileSync('npm', ['pack', '--pack-destination', destination, '--json'], { cwd: root, encoding: 'utf8' }); const tarball = path.join(destination, JSON.parse(json)[0].filename); const clean = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-clean-')); const noPython = fs.mkdtempSync(path.join(os.tmpdir(), 'installer-no-python-')); fs.writeFileSync(path.join(noPython, 'python3'), '#!/bin/sh\nexit 127\n', { mode: 0o755 }); const env = { ...process.env, PATH: `${noPython}:${path.dirname(process.execPath)}:/bin:/usr/bin` }; execFileSync('npm', ['install', '--ignore-scripts', '--no-package-lock', tarball], { cwd: clean, env, stdio: 'ignore' }); const help = execFileSync('node_modules/.bin/workflow-spec-driven', ['--help'], { cwd: clean, env, encoding: 'utf8' }); assert.match(help, /workflow-spec-driven install/); const module = await import(pathToFileURL(path.join(clean, 'node_modules/.bin/workflow-spec-driven')).href); const answers = ['1', 'n']; const stdin = { isTTY: true }; const stdout = { isTTY: true, write() {} }; const result = await module.main(['install'], { stdin, stdout, stderr: { write() {} }, targetRoot: clean, sourceRoot: path.join(clean, 'node_modules/workflow-spec-driven'), readline: { question: async () => answers.shift(), close() {} }, requireGit: false }); assert.equal(result, 0); assert.equal(fs.existsSync(path.join(clean, 'node_modules/workflow-spec-driven/scripts/adopt.py')), false); });
